id: IA5404AE4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T06:49:54+00:00'
last_modified: '2022-06-08T01:05:28.781385+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21619
  title: བྱང་ཆུབ་གཞུང་ལམ་དང་རྩ་ལྟུང་རྣམ་བཤད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    81E6:
      image_group_id: I5799
      title: ''
      total_pages: 422
      order: 1
      base_file: 81E6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
